name: Java CI with Maven and Docker in Linux

on:
 push:
    branches:
      - main
 pull_request:

jobs:
 build:
    runs-on: ubuntu-latest
    name: Build in Linux
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK  8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: mvn -f pom.xml verify -Pdocker
